import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Obaidullah Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark" lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-xl mx-auto">
          <Navbar />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
